name: Publish to marketplace

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm i -g vsce
    - run: vsce publish -p ${{ secrets.VSCE_TOKEN }}